### ISSUE TITLE
Add General section  

### ISSUE THREAD

**Issue by SAMYAK99** [MMIL/NewsRecital#11]
Describe the bug
Currently NewsRecital has all the sections including Health , Business etc... but it is missing General news category section

To Reproduce

1.  Navigate to home page
2. General news category is missing  

Expected behavior
General news category section should be added like other sections with no change in the UI

![Screenshot_2020-10-07-18-08-35-424_com projects game mobile news_retic](https://user-images.githubusercontent.com/54956876/95780021-c743fe00-0ce8-11eb-975a-371eeaf33926.jpg)

**Comment by raziqfarid** [comment]
@SAMYAK99  Please assign this issue for me

**Comment by raziqfarid** [comment]
@SAMYAK99 Do you want to place the General section before the Explore or after it?

**Comment by SAMYAK99** [comment]
@raziqfarid Add General news category section after "World" Tab !

**Comment by raziqfarid** [comment]
@SAMYAK99 I had added the 'General' Tab but it turns out that even-though I specific the category as 'general' in the api. The API is providing same data for both the Explore and General Tabs
