### ISSUE TITLE
Reduce size of app icon in Splash Screen 

### ISSUE THREAD

**Issue by SAMYAK99** [MMIL/NewsRecital#12]
# Describe the bug
Currently the size of the icon in Splash Screen is 180x180 .

# To Reproduce
1. Open the app 
2. See the icon in splash screen

# Expected behavior
Size of the icon should be changed to 150x150 

![Screenshot_2020-10-07-18-20-28-700_com projects game mobile news_retic](https://user-images.githubusercontent.com/54956876/95780789-2a826000-0cea-11eb-943e-d52f524612b1.jpg)

**Comment by EANimesha** [comment]
I like to contribute. Assign me

**Comment by SAMYAK99** [comment]
Go Ahead 😀
