### ISSUE TITLE
Handle  back pressed Navigation for TTS

### ISSUE THREAD

**Issue by SAMYAK99** [MMIL/NewsRecital#14]
# Describe the bug
Voice assistance continue to play even after the screen is pop backed .   

# To Reproduce

1 .Open the app
2. Click on any article
3. Tap on play button 
4. Suddenly Navigate back to the home screen using the back arrow button on top
5. See bug

# Expected Behavior
Voice assistance should immediately stop when back arrow button on top is pressed .

![Screenshot_2020-10-07-18-09-03-386_com projects game mobile news_retic](https://user-images.githubusercontent.com/54956876/95781478-839ec380-0ceb-11eb-8713-f90bddb02d53.jpg)

**Comment by akshay512** [comment]
I just created a PR please review it I hope it solves the issue, stopped the tts and it returns to the homescreen on press of back icon..
