### ISSUE TITLE
Overlapping UI contents .

### ISSUE THREAD

**Issue by SAMYAK99** [MMIL/NewsRecital#15]
# Describe the bug
Trying out the web version of flutter , I accidently messed up the UI with the mobile version , as a result the content and text are overlapping .  

# To Reproduce

1 .Open the app
2. Navigate through some articles 
3. See bug

# Expected Behavior
Fix this bug . Contents should not overlap .  Accordingly adjust the size and padding . 

![Screenshot_2020-10-12-23-58-48-286_com projects game mobile news_retic](https://user-images.githubusercontent.com/54956876/95783001-95ce3100-0cee-11eb-93cd-8750bbdd30da.jpg)

**Comment by SAMYAK99** [comment]
For Your Convince I have added some hints to fix this issue  in the designated file . Either you can follow this OR you can implement any other method 😀

**Comment by davidfranquet** [comment]
#18 this one should fix this
