### ISSUE TITLE
Date Format for News

### ISSUE THREAD

**Issue by dheerajkotwani** [MMIL/NewsRecital#19]
**Issue**
Currently the News Items have the Default date of Format "yyyy-MM-dd'T'HH:mm:sss'Z'"

**Changes**
The Date can be formated to something like 'hh:mm a   •   dd MMM yyyy' or similar to it as its recommended by Material Design,
 eg: 10:00 am  •  13 Oct 2020

**Screenshot containing the current format**
![news ratical](https://user-images.githubusercontent.com/44086235/95878430-d4b5c280-0d92-11eb-8555-728f4808f32a.jpg)

**Comment by SAMYAK99** [comment]
Yes ! This date can be modified . Would you like to fix this issue ?

**Comment by dheerajkotwani** [comment]
Yes, I would like to work on it.
